### ISSUE TITLE
Cannot add A records

### ISSUE THREAD

**Issue by frozenfoxx** [camptocamp/puppet-bind#60]
I'm currently having an issue adding A records to the configuration.  I'm using Puppet 4, Hiera 3, and receive the error below.  Also tried manually specifying this all in the Puppet code, no change in error.  Configuration details are also listed, not sure what I'm doing wrong.  If it's a case of improper use could there be an update issued to the README?  Thanks much for your help.

> *"Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid relationship: File[/opt/puppetlabs/puppet/cache/concat/_etc_bind_pri_somecompany.com.conf/fragments/10_somecompany.A.hosts] { notify => Exec[concat_/etc/bind/pri/somecompany.com.conf] }, because Exec[concat_/etc/bind/pri/somecompany.com.conf] doesn't seem to be in the catalog."*

__hiera__
```
---
ddnskeys:
  'dhcpupdate':
    secret:                     "XXXXXXXXXXXXXXXXXXXXXXXXXX"
ddnszones:
  'somecompany.com':
    zone_contact:               'hostmaster.somecompany.com'
    zone_ns:
      - 'dns.somecompany.com'
    zone_serial:                '2015121001'
    zone_ttl:                   '604800'
    is_dynamic:                 true
    allow_update:
      - 'dhcpupdate'
  '11.10.in-addr.arpa':
    zone_contact:               'hostmaster.somecompany.com'
    zone_ns:
      - 'dns.somecompany.com'
    zone_serial:                '2015121001'
    zone_ttl:                   '604800'
    is_dynamic:                 true
    allow_update:
      - 'dhcpupdate'
ddnsarecords:
  'hosts':
    zone:                       'somecompany.com'
    ptr:                        false
    zone_arpa:                  '168.192.in-addr.arpa'
    hash_data:
      dns:
        owner:                  '192.168.1.28'
```

__puppet__
```
class profile::bind {
  # Store hashes for resource realization
  $bindkeys = hiera_hash('ddnskeys')
  $zones    = hiera_hash('ddnszones')
  $arecords = hiera_hash('ddnsarecords')

  class { '::bind': }
  create_resources('bind::key', $bindkeys)
  create_resources('bind::a', $arecords, {})
  create_resources('bind::zone', $zones, {})
}
```

**Comment by cjeanneret** [comment]
weird — you might want to create the zone before the key/a resources, but we didn't see this kind of error on our side… Are you sure the zone name is correct for all resources?

**Comment by cjeanneret** [comment]
Closing, as no more information about this issue, and this didn't show up in acceptance tests.
