### ISSUE TITLE
should allow forwarders in zone_type master

### ISSUE THREAD

**Issue by felipe1982** [camptocamp/puppet-bind#63]
My master has

```
options {
        forwarders { 203.12.160.35; 203.12.160.36; };
       [......]
```

so that it can lookup stuff for the network which it does not control, or know about.

This should be configurable in puppet module. Thanks.

**Comment by cjeanneret** [comment]
Hello,

Normally release 1.4.0 enables a more convenient way to set options/configuration for named service. We still have to add some doc in the README about that, but you might find some usage in [this specific acceptance test](https://github.com/camptocamp/puppet-bind/blob/master/spec/acceptance/bind_cache_spec.rb).

Hope this helps your needs.

Cheers,

C.
