### ISSUE TITLE
Dynamic zones how are they supposed to work ?

### ISSUE THREAD

**Issue by zonArt** [camptocamp/puppet-bind#80]
Hi,

I'm not fully sure to understand how dynamic zones are supposed to work without an A record. This issue might directly be linked to #76. The actual behavior is the following: when having a dynamic zone (at least configured the way I did it), bind is starting but is not loading the dynamic zone because of missing A record:
`25-Jul-2017 14:20:04.632 general: error: zone foo.bar/IN/default: NS 'foo-bar' has no address records (A or AAAA)`.
Could you help me solve the issue ? Did anyone succeeded in having a dynamic zone working with this module ?

**Comment by zonArt** [comment]
I found some kind of ugly hack with setting up `zone_contact => <user>.localhost` and `zone_ns => ['localhost']`. But it looks counter intuitive and not that clean but it does the job.
To give a little more info, version of bind used is the 9.9.5 (and I somewhere in the init manifest that it was only compatible with version 9.7.1 and hardly with 9.7.2)

**Comment by zonArt** [comment]
@raphink Could I kindly ask you for help on that topic ? Is the hack the good way to go ?

**Comment by zonArt** [comment]
Leave it with my ugly hack, I guess after three years there is not much support I can hope to receive

**Comment by raphink** [comment]
I'm sorry this issue slipped between my reviews 😕

Could you paste the entire bit of code you're using?
